<?php
/**
 *
 * Piwik Extension for Magento created by Adrian Speyer
 * Get Piwik at http://www.piwik.org - Open source web analytics
 *
 * @category    design
 * @package     base_default_template_piwikanalytics_piwik
 * @copyright   Copyright (c) 2012 Adrian Speyer. (http://www.adrianspeyer.com)
 * @license http://www.gnu.org/licenses/gpl-3.0.html GPL v3 or later
 *
 */
?>
<?php if (!Mage::helper('core/cookie')->isUserNotAllowSaveCookie()): ?>
    <?php $siteId = Mage::getStoreConfig(PiwikMage_PiwikAnalytics_Helper_Data::XML_PATH_SITE) ?>
    <?php $installPath = Mage::getStoreConfig(PiwikMage_PiwikAnalytics_Helper_Data::XML_PATH_INSTALL) ?>

    <?php

    if ($siteId) {
        
        /*remove https or https*/
	   $installPath = preg_replace('#^https?:#', '', $installPath);
        

        // 0 Search Results
        if($this->getRequest()->getControllerName()=='result') {
            $noRes = Mage::helper('catalogsearch')->getEngine()
                                                  ->getResultCollection()
                                                  ->addSearchFilter(Mage::helper('catalogsearch')
                                                  ->getQuery()
                                                  ->getQueryText())
                                                  ->getSize();
        }
        ?>

        <!-- START PIWIK TRACKING CODE -->
        <script type="text/javascript">
            //<![CDATA[
            var _paq = _paq || [];
            (function(){ 
				var u="<?php echo $installPath ?>";
			    _paq.push(['setSiteId', <?php echo $siteId ?>]);
                _paq.push(['setTrackerUrl', u+'piwik.php']);
                <?php echo $this->_getEcommerceCartUpdate()?>
                <?php echo $this->_getOrdersTrackingCode()?>
                <?php echo $this->_getProductPageview()?>
                <?php echo $this->_getCategoryPageview()?>

                <?php if (isset($noRes)): ?>
                _paq.push(['setCustomUrl', '' + document.URL + '&search_count=<?php echo $noRes ?>']);
                <?php endif ?>

                <?php
                //404 tracking
                $action = Mage::app()->getRequest()->getActionName();
                if($action == 'noRoute'){?>
                _paq.push(['setDocumentTitle', '404/URL = '+String(document.location.pathname+document.location.search).replace(/\//g,"%2f") + '/From = ' + String(document.referrer).replace(/\//g,"%2f")]);
                <?php }?>

                _paq.push(['trackPageView']);
                _paq.push(['enableLinkTracking']);
                var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript'; g.defer=true; g.async=true; g.src=u+'piwik.js';
                s.parentNode.insertBefore(g,s); })();
        </script>
        <noscript><p><img src="<?php echo $installPath ?>piwik.php?idsite=<?php echo $siteId ?>" style="border:0" alt="" /></p></noscript>
        <!-- END PIWIK TRACKING CODE -->

    <?php } ?>
<?php endif; ?>
